# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20171202_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='painting_image',
            field=models.FileField(upload_to='documents/%Y/%m'),
        ),
    ]
